---

- hosts: localhost
  connection: local
  gather_facts: true
  become: yes

  roles:
    - cis
  vars:
    cis_level_1_exclusions:
      - 2.1.1
      - 2.1.2
      - 2.1.3
      - 2.1.4
      - 2.1.5
      - 2.1.6
      - 2.1.7
      - 2.1.8
      - 2.1.9
      - 2.1.10
      - 2.1.11  
      - 2.2.3
      - 2.2.4
      - 2.2.5
      - 2.2.6
      - 2.2.8
      - 2.2.9
      - 2.2.10
      - 2.2.11
      - 2.2.12
      - 2.2.13
      - 2.2.14
      - 2.2.16
      - Check if prelink binary exists
      - 1.1.19
      - 1.5.4
      - 3.4.2
      - 3.4.3
      - 3.6.2
      - 5.3.2
